name: flutter_web_demo
description: Flutter Web App Demo

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.3.2
  built_value: ^7.1.0
  http: ^0.12.2

dev_dependencies:
  build_runner: ^1.10.1
  built_value_generator: ^7.1.0
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - icons/
